In [31]:
import numpy as np
from sklearn.cluster import AgglomerativeClustering
import os

ground_truth = [0,1,2,3,1,1,1,1,4,1,4,2,3,2,1,1,3,3,1,2,2]
#camera 1 = [1,3,4,5,6,7,8,9,10,11,14,16,17,18,20,21] real
#camera 1 = [1,2,2,2,2,1,3,3, 1, 1, 1, 2, 1, 2, 0, 0] clusterd
camera_1_dict = {0:[20,21],
                 1:[1,7,10,11,14,17],
                 2:[3,4,5,6,16,18],
                 3:[8,9]
                 }
#camera 2 = [1,2,5,6,7,8,12,13,14,16,20,21,23,24,25,29,31,34,35,36,38,39,44,47,49,53,54,55,56,57,58,59,61] real
#camera 2 = [0,1,2,3,1,3, 4, 1, 4, 5, 5, 1, 1, 0, 3, 1, 5, 5, 4, 5, 1, 1, 0, 1, 0, 1, 0, 5, 1, 0, 0, 0, 0] clusterd
camera_2_dict = {0:[1,24,44,49,54,57,58,59,61],
                 1:[2,7,13,21,23,29,38,39,47,53,56],
                 2:[5],
                 3:[6,8,25],
                 4:[12,14,35],
                 5:[16,20,31,34,36,55]
                 }
# ground_truth = [1,0,2,3,1,1,4,4,1 ,1,1 ,0 ,1 , 0,4 ,0 ]

In [5]:
import os
input_dir = '/home/user_219/omer_gil/BoT-SORT/best_images_parts_embeddings/2'
a = list(map(int,sorted(os.listdir(input_dir), key=int)))

['1',
 '2',
 '5',
 '6',
 '7',
 '8',
 '12',
 '13',
 '14',
 '16',
 '20',
 '21',
 '23',
 '24',
 '25',
 '29',
 '31',
 '34',
 '35',
 '36',
 '38',
 '39',
 '44',
 '47',
 '49',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '61']

In [32]:
len(ground_truth)

16

In [33]:
def remap_array(arr):
    # Get the unique numbers in the array and sort them
    unique_sorted = sorted(set(arr))

    mapping = {}
    for num in arr:
        if num not in mapping:
            mapping[num] = unique_sorted[0]
            unique_sorted = unique_sorted[1:]
        
    # Remap the array using the mapping
    remapped_arr = [mapping[num] for num in arr]
    
    return remapped_arr

In [34]:
input_dir = '/home/user_219/omer_gil/BoT-SORT/best_images_parts_embeddings/1'
heads = []
upper = []
shoes_r = []
shoes_l = []
for dir in sorted(os.listdir(input_dir), key=int):
    path = os.path.join(input_dir, dir,"features.npy")
    features = np.load(path)
    heads.append(features[0])
    upper.append(features[1])
    shoes_r.append(features[2])
    shoes_l.append(features[2])
heads = np.array(heads)
upper = np.array(upper)
shoes_r = np.array(shoes_r)
shoes_l = np.array(shoes_l)

In [35]:
len(heads), len(upper), len(shoes_r), len(shoes_l)

(16, 16, 16, 16)

In [36]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import normalize

def Kmeans(data):
    # Normalize the data to unit vectors
    normalized_data = normalize(data, norm='l2')

    # Create a KMeans instance with 4 clusters, using KMeans++ for initialization
    kmeans = KMeans(n_clusters=6, init='k-means++', random_state=42)

    # Fit the model on the normalized data
    kmeans.fit(normalized_data)

    # Predict the clusters
    clusters = kmeans.predict(normalized_data)

    # Output the clusters each data point belongs to
    print("Cluster assignments:", remap_array(clusters))
    return clusters

heads_clusters = Kmeans(heads.reshape(16, 1600 * 768))
upper_clusters = Kmeans(upper.reshape(16, 1600 * 768))
shoes_r_clusters = Kmeans(shoes_r.reshape(16, 1600 * 768))
shoes_l_clusters = Kmeans(shoes_l.reshape(16, 1600 * 768))
print(ground_truth)


Cluster assignments: [0, 1, 1, 2, 1, 0, 1, 2, 3, 3, 4, 1, 4, 5, 1, 1]
Cluster assignments: [0, 1, 2, 3, 4, 2, 0, 3, 3, 3, 0, 1, 3, 5, 1, 2]
Cluster assignments: [0, 1, 2, 1, 2, 3, 4, 1, 5, 4, 0, 1, 3, 5, 5, 1]
Cluster assignments: [0, 1, 2, 1, 2, 3, 4, 1, 5, 4, 0, 1, 3, 5, 5, 1]
[1, 0, 2, 3, 1, 1, 4, 4, 1, 1, 1, 0, 1, 0, 4, 0]


In [37]:
print(remap_array(heads_clusters))
# print(remap_array(upper_clusters))
print(remap_array(shoes_r_clusters))
print(remap_array(shoes_l_clusters))
print(', '.join(map(str, np.array(ground_truth) -1)))

[0, 1, 1, 2, 1, 0, 1, 2, 3, 3, 4, 1, 4, 5, 1, 1]
[0, 1, 2, 1, 2, 3, 4, 1, 5, 4, 0, 1, 3, 5, 5, 1]
[0, 1, 2, 1, 2, 3, 4, 1, 5, 4, 0, 1, 3, 5, 5, 1]
0, -1, 1, 2, 0, 0, 3, 3, 0, 0, 0, -1, 0, -1, 3, -1


In [ ]:
print(remap_array(heads_clusters))
# print(remap_array(upper_clusters))
print(remap_array(shoes_r_clusters))
print(remap_array(shoes_l_clusters))
print(', '.join(map(str, np.array(ground_truth) -1)))

[0, 1, 1, 2, 1, 0, 1, 2, 3, 3, 4, 1, 4, 2, 1, 1]
[0, 1, 2, 1, 2, 2, 2, 3, 3, 2, 0, 1, 2, 4, 4, 1]
[0, 1, 2, 1, 2, 2, 2, 3, 3, 2, 0, 1, 2, 4, 4, 1]
0, -1, 1, 2, 0, 0, 3, 3, 0, 0, 0, -1, 0, -1, 3, -1


In [38]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import AgglomerativeClustering


def cluster(data):
    # Compute the cosine similarity matrix
    cosine_sim_matrix = cosine_similarity(data)

    # Convert similarity to distance
    cosine_dist_matrix = 1 - cosine_sim_matrix

    # Create an Agglomerative Clustering model that uses the precomputed distance matrix
    cluster = AgglomerativeClustering(n_clusters=5, affinity='precomputed', linkage='average')
    # cluster = AgglomerativeClustering( affinity='precomputed', linkage='average')

    # Fit model to the distance matrix
    clusters = cluster.fit_predict(cosine_dist_matrix)

    # Output the clusters each data point belongs to
    print("Cluster assignments:", remap_array(clusters))
    return remap_array(clusters)
clustering_heads = cluster(heads.reshape(16, 1600 * 768))
clustering_upper = cluster(upper.reshape(16, 1600 * 768))
shoes_r_clusters = cluster(shoes_r.reshape(16, 1600 * 768))
shoes_l_clusters = cluster(shoes_l.reshape(16, 1600 * 768))

# clustering_heads = AgglomerativeClustering(distance_threshold=80,n_clusters=None).fit(heads.reshape(21, 1600 * 768))
# clustering_upper = AgglomerativeClustering(distance_threshold=80,n_clusters=None).fit(upper.reshape(21, 1600 * 768))
# clustering_shoes = AgglomerativeClustering(distance_threshold=80,n_clusters=None).fit(shoes.reshape(21, 1600 * 768))


Cluster assignments: [0, 1, 1, 0, 1, 0, 1, 0, 2, 2, 3, 1, 3, 4, 1, 1]
Cluster assignments: [0, 1, 2, 2, 3, 2, 4, 2, 2, 2, 0, 1, 2, 0, 1, 2]
Cluster assignments: [0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 3, 4, 0, 2, 2, 1]
Cluster assignments: [0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 3, 4, 0, 2, 2, 1]


In [39]:

print(clustering_heads)
print(clustering_upper)
print(shoes_r_clusters)
print(shoes_l_clusters)
print(', '.join(map(str, np.array(ground_truth) -1)))


[0, 1, 1, 0, 1, 0, 1, 0, 2, 2, 3, 1, 3, 4, 1, 1]
[0, 1, 2, 2, 3, 2, 4, 2, 2, 2, 0, 1, 2, 0, 1, 2]
[0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 3, 4, 0, 2, 2, 1]
[0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 3, 4, 0, 2, 2, 1]
0, -1, 1, 2, 0, 0, 3, 3, 0, 0, 0, -1, 0, -1, 3, -1


In [42]:
a=remap_array(clustering_heads.labels_)
b=remap_array(clustering_upper.labels_)
c=remap_array(clustering_shoes.labels_)
for i in range(21):
    print(a[i],b[i],c[i])




0 0 0
1 1 1
0 2 2
2 3 3
3 4 4
0 5 5
4 6 6
0 7 7
5 8 8
6 9 8
7 10 8
8 11 9
0 12 10
9 13 11
10 14 8
11 15 12
12 16 13
13 17 14
14 18 15
0 19 8
15 20 16


In [22]:
clustering.labels_

array([ 0, 11,  0,  8, 13,  0, 15,  0,  9, 14, 12, 10,  0,  5,  6,  7,  3,
        4,  1,  0,  2])

In [14]:
heads[1]

array([[ 3.2287986 ,  0.45867094,  1.3736802 , ..., -0.23640008,
         0.93399197, -2.1161773 ],
       [ 3.4706018 , -0.2221838 ,  1.1400833 , ..., -0.23340522,
         1.0758767 , -2.9382463 ],
       [ 3.5105214 , -2.3424265 , -1.7820073 , ..., -1.1882707 ,
        -0.76799697, -3.3912196 ],
       ...,
       [ 2.4713593 ,  3.4192903 ,  1.4926487 , ...,  0.02191871,
        -1.9690161 ,  0.41913792],
       [ 2.20063   ,  0.2385513 , -0.58404046, ...,  0.15117496,
         0.14676309, -1.6007402 ],
       [ 2.4690068 , -0.19914155,  0.07684889, ..., -0.06813555,
        -0.09314284, -1.6499184 ]], dtype=float32)

In [15]:
heads[2]

array([[ 1.1438075 , -2.1969113 , -0.83005995, ..., -1.0722204 ,
        -1.24343   , -0.01209161],
       [ 1.1134405 , -2.2205548 , -0.8173429 , ..., -1.1128546 ,
        -1.3035482 ,  0.03927336],
       [ 1.6596313 , -3.4989223 , -2.6044834 , ..., -1.7516901 ,
        -1.113846  ,  0.79138356],
       ...,
       [ 2.5161543 , -2.9868627 , -4.0463185 , ..., -1.9385047 ,
        -1.1112903 ,  1.0280489 ],
       [ 3.4570374 , -3.3327248 , -4.1776085 , ..., -2.2550433 ,
        -0.38078147, -0.25140765],
       [ 3.2726593 , -3.6322274 , -3.7357962 , ..., -2.467514  ,
        -0.4626041 , -0.70267695]], dtype=float32)

In [16]:
heads[5]


array([[ 1.1438041 , -2.1969023 , -0.83004695, ..., -1.0722181 ,
        -1.243423  , -0.0120911 ],
       [ 1.1134411 , -2.220555  , -0.8173449 , ..., -1.112855  ,
        -1.3035468 ,  0.03927228],
       [ 1.6596276 , -3.498918  , -2.6044838 , ..., -1.751687  ,
        -1.1138479 ,  0.7913776 ],
       ...,
       [ 2.5161572 , -2.9868665 , -4.04632   , ..., -1.9385026 ,
        -1.1112881 ,  1.0280421 ],
       [ 3.4570343 , -3.3327248 , -4.1776137 , ..., -2.2550437 ,
        -0.3807817 , -0.25140706],
       [ 3.2726576 , -3.6322331 , -3.7357922 , ..., -2.467513  ,
        -0.4626092 , -0.70268315]], dtype=float32)

In [17]:
def cluster_cosine(data):
    cluster = AgglomerativeClustering(distance_threshold = None,n_clusters = 5)
    # cluster = AgglomerativeClustering(n_clusters = 5, metric='cosine',distance_threshold = None,linkage='average')
    # Fit model to the distance matrix
    clusters = cluster.fit_predict(data)
    return clusters

clustering_heads = cluster_cosine(heads.reshape(21, 1600 * 768))
clustering_upper = cluster_cosine(upper.reshape(21, 1600 * 768))
clustering_shoes = cluster_cosine(shoes.reshape(21, 1600 * 768))
print(remap_array(clustering_heads))
# print(remap_array(clustering_upper))
print(remap_array(clustering_shoes))
print(ground_truth)

[0, 1, 0, 2, 2, 0, 2, 0, 2, 3, 3, 4, 0, 2, 1, 2, 0, 2, 3, 0, 3]
[0, 1, 2, 3, 2, 0, 3, 2, 4, 4, 4, 4, 1, 3, 4, 3, 3, 3, 3, 4, 2]
[0, 1, 2, 3, 1, 1, 1, 1, 4, 1, 4, 2, 3, 2, 1, 1, 3, 3, 1, 2, 2]
